name: "Code check with ruff"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]


concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-22.04]
            python-version: ["3.10"]

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff


    - name: Test with ruff
      run: |
        ruff check .
        ruff format .