name: Docker Image CI

on:
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

jobs:
    build_docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up DVC
              uses: iterative/setup-dvc@v1
        
            - name: Get data
              run: dvc pull
              env:
                GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

            - name: Build the Docker image
              run: |
                echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
                docker build . --file dockerfiles/trainer.dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
                docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
            
            - name: Run container
              run: |
                docker run lucasmogsan/trainer:latest